version: '3.8'

services:
  ai-docs-search:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - /:/host:ro  # Mount entire host filesystem as read-only
      - ../data/db:/app/data/db  # Mount database directory for persistence
      - ..:/app  # Mount current directory as /app
    environment:
      - HOST_ROOT=/host  # Reference point for the host filesystem
      - PYTHONPATH=/app/src:$PYTHONPATH
    command: ["python", "src/app.py"]
    stdin_open: true
    tty: true        # Allocate a pseudo-TTY 